import { fileURLToPath } from "node:url";

import { defineConfig } from "vitest/config";
import { rejectNextRuntimeInternals, vinextTestAliases } from "./tests/vinext-test-runtime.ts";

export default defineConfig({
  plugins: [rejectNextRuntimeInternals()],
  resolve: {
    alias: {
      "@": fileURLToPath(new URL("./src", import.meta.url)),
      // The real document is generated by the vite plugin in `tools/`, which this runner never loads.
      "virtual:api-openapi-document": fileURLToPath(
        new URL("./tests/fixtures/api-openapi-document.ts", import.meta.url)
      ),
      ...vinextTestAliases,
    },
  },
  test: {
    environment: "node",
    // `tools/` holds build-time vite plugins and `scripts/` CI helpers; both co-locate their tests.
    include: ["src/**/*.test.ts", "tools/**/*.test.ts", "scripts/**/*.test.mjs"],
    reporters: process.env.GITHUB_ACTIONS === "true" ? ["dot", "github-actions"] : ["default"],
  },
});
