// Generated by `pnpm logo:generate` from src/constants/logo.ts — do not edit by hand.
// A hash of the rendered email logo: identical artwork regenerates to an identical file.

export const LOGO_VERSION = "93d652ad3e02";
