import { createHash } from "node:crypto";

import { EMAIL_LOGO, renderLogoSvg, SITE_LOGO } from "@/constants/logo";

// The places the brand mark has to exist as a file rather than as markup a component renders: the
// Next.js icon conventions, and a plain asset a fork can hand to anything outside the app. All are
// generated, so `src/constants/logo.ts` stays the only copy of the geometry.

/** Ten times the tight bounds (27 x 24.8), so the file has whole-pixel intrinsic dimensions. */
const BRAND_ASSET_SIZE = { width: 270, height: 248 } as const;
const FAVICON_SIZE = { width: 32, height: 32 } as const;

/** Square entries packed into the .ico. 48 is the largest size Windows asks a favicon for. */
export const FAVICON_ICO_SIZES = [16, 32, 48] as const;

/** Side of the master bitmap every .ico entry is downscaled from. Over 20x the largest entry. */
export const FAVICON_RASTER_SIZE = 1024;

export const FAVICON_ICO_PATH = "src/app/favicon.ico";

export const EMAIL_LOGO_PNG_PATH = `public${EMAIL_LOGO.pathname}`;

export const LOGO_VERSION_PATH = "src/constants/logo-version.ts";

/** Enough hex to make a collision between two brand marks impossible in practice. */
const LOGO_VERSION_LENGTH = 12;

const GENERATED_BY = "Generated by `pnpm logo:generate` from src/constants/logo.ts — do not edit by hand.";

/**
 * The cache buster the emails append to the logo URL. Derived from the artwork rather than from the
 * clock: mail image proxies hold a URL for a long time and ignore our headers, so the URL has to
 * change when the artwork does — and only then, or every recipient refetches and each message
 * carries a URL unique enough to reveal who opened it. A no-op regeneration must not diff.
 */
export function computeLogoVersion(): string {
  return createHash("sha256")
    .update(renderEmailLogoRasterSvg(), "utf8")
    .digest("hex")
    .slice(0, LOGO_VERSION_LENGTH);
}

export function renderLogoVersionModule({ version }: { version: string }): string {
  return [
    `// ${GENERATED_BY}`,
    `// A hash of the rendered email logo: identical artwork regenerates to an identical file.`,
    ``,
    `export const LOGO_VERSION = "${version}";`,
    ``,
  ].join("\n");
}

export interface LogoAsset {
  /** Project-relative, POSIX separators — the path this file is written to and read back from. */
  path: string;
  contents: string;
}

function buildAsset({
  path,
  size,
  note = [],
}: {
  path: string;
  size: { width: number; height: number };
  note?: readonly string[];
}): LogoAsset {
  const comment = [GENERATED_BY, ...note].join("\n     ");

  return { path, contents: `<!-- ${comment} -->\n${renderLogoSvg({ size })}\n` };
}

export const LOGO_ASSETS: readonly LogoAsset[] = [
  buildAsset({
    path: "src/app/icon.svg",
    size: FAVICON_SIZE,
    note: [
      "Tight viewBox and no backing tile on purpose: at 16px the three planes stay separable this",
      "way, while any tile fuses them into a single diagonal slash.",
    ],
  }),
  buildAsset({ path: "public/logo.svg", size: BRAND_ASSET_SIZE }),
];

/**
 * Markup the .ico entries are rasterized from. Square, like `src/app/icon.svg`, so the letterboxing
 * the tight viewBox produces is identical in both files and the mark does not shift between them.
 */
export function renderFaviconRasterSvg(): string {
  return renderLogoSvg({ size: { width: FAVICON_RASTER_SIZE, height: FAVICON_RASTER_SIZE } });
}

/**
 * Markup `public/logo.png` is rasterized from. Rectangular, on the tight bounds, because the email
 * header sizes the <img> to the artwork — the letterboxing the square favicon needs would read
 * there as stray padding the template cannot see or centre against.
 */
export function renderEmailLogoRasterSvg(): string {
  return renderLogoSvg({ size: SITE_LOGO });
}
